import photo1 from "../../assets/data/1.jpg";
import photo2 from "../../assets/data/2.jpg";
import photo3 from "../../assets/data/3.jpg";
import photo4 from "../../assets/data/4.jpg";
import photo5 from "../../assets/data/5.jpg";
import photo6 from "../../assets/data/6.jpg";
import photo7 from "../../assets/data/7.jpg";
import photo8 from "../../assets/data/8.jpg";
import photo9 from "../../assets/data/9.jpg";
import photo10 from "../../assets/data/10.jpg";
import photo11 from "../../assets/data/11.jpg";
import photo12 from "../../assets/data/12.jpg";
import photo13 from "../../assets/data/13.png";
import photo14 from "../../assets/data/14.jpg";
import photo15 from "../../assets/data/15.jpg";
import photo16 from "../../assets/data/16.jpg";
import photo17 from "../../assets/data/17.jpg";
import photo18 from "../../assets/data/18.jpg";
import photo19 from "../../assets/data/19.jpg";
import photo20 from "../../assets/data/20.jpg";

export const fallbackProducts = [
  {
    productId: 1,
    customerId: 11,
    detailCategoryId: 2,
    productName: "딸기",
    productDescription: "당도 높은 국내산 딸기, 500g 한 팩",
    productImage: photo1,
    baseDiscountRate: 20,
    regularDiscountRate: 25,
    productPrice: 12000,
    calculatedBasePrice: 9000,
    isRegularSale: "ACTIVE",
    reviewCount: 63,
    averageScore: 4.5,
    soldOut: false,
    storeName: "슬기네",
  },
  {
    productId: 2,
    customerId: 12,
    detailCategoryId: 3,
    productName: "사과",
    productDescription: "아삭한 청송 사과, 3kg 박스",
    productImage: photo2,
    baseDiscountRate: 15,
    regularDiscountRate: 18,
    productPrice: 25000,
    calculatedBasePrice: 20500,
    isRegularSale: "ACTIVE",
    reviewCount: 42,
    averageScore: 4.2,
    soldOut: false,
    storeName: "행복과수",
  },
  {
    productId: 3,
    customerId: 13,
    detailCategoryId: 4,
    productName: "바나나",
    productDescription: "필리핀 산 달콤한 바나나, 1kg",
    productImage: photo3,
    baseDiscountRate: 10,
    regularDiscountRate: 12,
    productPrice: 5000,
    calculatedBasePrice: 4400,
    isRegularSale: "ACTIVE",
    reviewCount: 88,
    averageScore: 4.7,
    soldOut: false,
    storeName: "과일마을",
  },
  {
    productId: 4,
    customerId: 14,
    detailCategoryId: 5,
    productName: "토마토",
    productDescription: "무농약 완숙 토마토, 2kg 박스",
    productImage: photo4,
    baseDiscountRate: 18,
    regularDiscountRate: 22,
    productPrice: 15000,
    calculatedBasePrice: 11700,
    isRegularSale: "ACTIVE",
    reviewCount: 56,
    averageScore: 4.3,
    soldOut: false,
    storeName: "신선채소",
  },
  {
    productId: 5,
    customerId: 15,
    detailCategoryId: 6,
    productName: "오렌지",
    productDescription: "미국산 고당도 오렌지, 10개입",
    productImage: photo5,
    baseDiscountRate: 12,
    regularDiscountRate: 15,
    productPrice: 18000,
    calculatedBasePrice: 15300,
    isRegularSale: "ACTIVE",
    reviewCount: 37,
    averageScore: 4.1,
    soldOut: false,
    storeName: "과일천국",
  },
  {
    productId: 6,
    customerId: 16,
    detailCategoryId: 7,
    productName: "당근",
    productDescription: "제주산 유기농 당근, 1kg 팩",
    productImage: photo6,
    baseDiscountRate: 8,
    regularDiscountRate: 10,
    productPrice: 6000,
    calculatedBasePrice: 5400,
    isRegularSale: "ACTIVE",
    reviewCount: 29,
    averageScore: 4.0,
    soldOut: false,
    storeName: "직송마켓",
  },
  {
    productId: 7,
    customerId: 17,
    detailCategoryId: 8,
    productName: "양파",
    productDescription: "국내산 중품 양파, 3kg 망",
    productImage: photo7,
    baseDiscountRate: 25,
    regularDiscountRate: 30,
    productPrice: 10000,
    calculatedBasePrice: 7000,
    isRegularSale: "ACTIVE",
    reviewCount: 72,
    averageScore: 4.6,
    soldOut: false,
    storeName: "채소농장",
  },
  {
    productId: 8,
    customerId: 18,
    detailCategoryId: 9,
    productName: "포도",
    productDescription: "씨없는 청포도, 2kg 박스",
    productImage: photo8,
    baseDiscountRate: 15,
    regularDiscountRate: 18,
    productPrice: 22000,
    calculatedBasePrice: 18000,
    isRegularSale: "ACTIVE",
    reviewCount: 51,
    averageScore: 4.4,
    soldOut: false,
    storeName: "달콤과일",
  },
  {
    productId: 9,
    customerId: 19,
    detailCategoryId: 10,
    productName: "고구마",
    productDescription: "호박고구마, 5kg 박스",
    productImage: photo9,
    baseDiscountRate: 20,
    regularDiscountRate: 23,
    productPrice: 20000,
    calculatedBasePrice: 15400,
    isRegularSale: "ACTIVE",
    reviewCount: 84,
    averageScore: 4.8,
    soldOut: false,
    storeName: "건강뿌리",
  },
  {
    productId: 10,
    customerId: 20,
    detailCategoryId: 11,
    productName: "키위",
    productDescription: "뉴질랜드산 골드키위, 10개입",
    productImage: photo10,
    baseDiscountRate: 10,
    regularDiscountRate: 12,
    productPrice: 15000,
    calculatedBasePrice: 13200,
    isRegularSale: "ACTIVE",
    reviewCount: 39,
    averageScore: 4.2,
    soldOut: false,
    storeName: "수입과일",
  },
  {
    productId: 11,
    customerId: 21,
    detailCategoryId: 12,
    productName: "감자",
    productDescription: "국내산 감자, 3kg 망",
    productImage: photo11,
    baseDiscountRate: 18,
    regularDiscountRate: 22,
    productPrice: 8000,
    calculatedBasePrice: 6200,
    isRegularSale: "ACTIVE",
    reviewCount: 67,
    averageScore: 4.5,
    soldOut: false,
    storeName: "알짜배기",
  },
  {
    productId: 12,
    customerId: 22,
    detailCategoryId: 13,
    productName: "블루베리",
    productDescription: "국내산 생 블루베리, 500g 팩",
    productImage: photo12,
    baseDiscountRate: 15,
    regularDiscountRate: 20,
    productPrice: 18000,
    calculatedBasePrice: 14400,
    isRegularSale: "ACTIVE",
    reviewCount: 45,
    averageScore: 4.6,
    soldOut: false,
    storeName: "베리굿팜",
  },
  {
    productId: 13,
    customerId: 23,
    detailCategoryId: 14,
    productName: "배추",
    productDescription: "국내산 절임배추, 10kg",
    productImage: photo13,
    baseDiscountRate: 22,
    regularDiscountRate: 25,
    productPrice: 30000,
    calculatedBasePrice: 22500,
    isRegularSale: "ACTIVE",
    reviewCount: 91,
    averageScore: 4.7,
    soldOut: false,
    storeName: "김장준비",
  },
  {
    productId: 14,
    customerId: 24,
    detailCategoryId: 15,
    productName: "파인애플",
    productDescription: "필리핀산 스위트 파인애플, 2kg",
    productImage: photo14,
    baseDiscountRate: 12,
    regularDiscountRate: 15,
    productPrice: 12000,
    calculatedBasePrice: 10200,
    isRegularSale: "ACTIVE",
    reviewCount: 33,
    averageScore: 4.1,
    soldOut: false,
    storeName: "트로피칼",
  },
  {
    productId: 15,
    customerId: 25,
    detailCategoryId: 16,
    productName: "깻잎",
    productDescription: "국내산 친환경 깻잎, 100g",
    productImage: photo15,
    baseDiscountRate: 8,
    regularDiscountRate: 10,
    productPrice: 3000,
    calculatedBasePrice: 2700,
    isRegularSale: "ACTIVE",
    reviewCount: 28,
    averageScore: 4.3,
    soldOut: false,
    storeName: "향긋채소",
  },
  {
    productId: 16,
    customerId: 26,
    detailCategoryId: 17,
    productName: "방울토마토",
    productDescription: "국내산 유기농 방울토마토, 1kg",
    productImage: photo16,
    baseDiscountRate: 20,
    regularDiscountRate: 25,
    productPrice: 10000,
    calculatedBasePrice: 7500,
    isRegularSale: "ACTIVE",
    reviewCount: 76,
    averageScore: 4.8,
    soldOut: false,
    storeName: "미니채소",
  },
  {
    productId: 17,
    customerId: 27,
    detailCategoryId: 18,
    productName: "수박",
    productDescription: "국내산 당도선별 수박, 8kg 내외",
    productImage: photo17,
    baseDiscountRate: 15,
    regularDiscountRate: 18,
    productPrice: 28000,
    calculatedBasePrice: 22960,
    isRegularSale: "ACTIVE",
    reviewCount: 58,
    averageScore: 4.5,
    soldOut: false,
    storeName: "달콤수박",
  },
  {
    productId: 18,
    customerId: 28,
    detailCategoryId: 19,
    productName: "버섯",
    productDescription: "국내산 버섯모둠 (새송이, 표고, 느타리), 500g",
    productImage: photo18,
    baseDiscountRate: 10,
    regularDiscountRate: 12,
    productPrice: 8000,
    calculatedBasePrice: 7040,
    isRegularSale: "ACTIVE",
    reviewCount: 41,
    averageScore: 4.2,
    soldOut: false,
    storeName: "버섯나라",
  },
  {
    productId: 19,
    customerId: 29,
    detailCategoryId: 20,
    productName: "양배추",
    productDescription: "국내산 유기농 양배추, 2kg",
    productImage: photo19,
    baseDiscountRate: 18,
    regularDiscountRate: 22,
    productPrice: 6000,
    calculatedBasePrice: 4680,
    isRegularSale: "ACTIVE",
    reviewCount: 52,
    averageScore: 4.4,
    soldOut: false,
    storeName: "신선채소",
  },
  {
    productId: 20,
    customerId: 30,
    detailCategoryId: 21,
    productName: "망고",
    productDescription: "태국산 애플망고, 5kg 박스",
    productImage: photo20,
    baseDiscountRate: 25,
    regularDiscountRate: 30,
    productPrice: 35000,
    calculatedBasePrice: 24500,
    isRegularSale: "ACTIVE",
    reviewCount: 87,
    averageScore: 4.9,
    soldOut: false,
    storeName: "과일천국",
  },
];
