export const fallbackProducts = [
  {
    productId: 1,
    customerId: 11,
    detailCategoryId: 2,
    productName: "딸기 - 이강인",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 16,
    regularDiscountRate: 21,
    productPrice: 91657,
    calculatedBasePrice: 76991,
    isRegularSale: "ACTIVE",
    reviewCount: 63,
    averageScore: 3.0,
    soldOut: false,
  },
  {
    productId: 2,
    customerId: 73,
    detailCategoryId: 7,
    productName: "복숭아 - 김민재",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 19,
    regularDiscountRate: 20,
    productPrice: 78843,
    calculatedBasePrice: 63862,
    isRegularSale: "INACTIVE",
    reviewCount: 65,
    averageScore: 3.0,
    soldOut: false,
  },
  {
    productId: 3,
    customerId: 72,
    detailCategoryId: 1,
    productName: "참외 - 이강인",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 18,
    regularDiscountRate: 25,
    productPrice: 38222,
    calculatedBasePrice: 31342,
    isRegularSale: "INACTIVE",
    reviewCount: 100,
    averageScore: 2.7,
    soldOut: false,
  },
  {
    productId: 4,
    customerId: 44,
    detailCategoryId: 9,
    productName: "수박 - 손흥민",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 5,
    regularDiscountRate: 13,
    productPrice: 18472,
    calculatedBasePrice: 17548,
    isRegularSale: "INACTIVE",
    reviewCount: 56,
    averageScore: 1.1,
    soldOut: false,
  },
  {
    productId: 5,
    customerId: 28,
    detailCategoryId: 8,
    productName: "포도 - 이강인",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 17,
    regularDiscountRate: 19,
    productPrice: 65801,
    calculatedBasePrice: 54614,
    isRegularSale: "ACTIVE",
    reviewCount: 7,
    averageScore: 4.4,
    soldOut: true,
  },
  {
    productId: 6,
    customerId: 96,
    detailCategoryId: 9,
    productName: "수박 - 이강인",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 8,
    regularDiscountRate: 13,
    productPrice: 60774,
    calculatedBasePrice: 55912,
    isRegularSale: "ACTIVE",
    reviewCount: 44,
    averageScore: 1.6,
    soldOut: false,
  },
  {
    productId: 7,
    customerId: 24,
    detailCategoryId: 5,
    productName: "배 - 손흥민",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 8,
    regularDiscountRate: 21,
    productPrice: 82857,
    calculatedBasePrice: 76228,
    isRegularSale: "ACTIVE",
    reviewCount: 60,
    averageScore: 2.4,
    soldOut: true,
  },
  {
    productId: 8,
    customerId: 82,
    detailCategoryId: 9,
    productName: "사과 - 이강인",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 15,
    regularDiscountRate: 29,
    productPrice: 22817,
    calculatedBasePrice: 19394,
    isRegularSale: "ACTIVE",
    reviewCount: 68,
    averageScore: 2.9,
    soldOut: true,
  },
  {
    productId: 9,
    customerId: 59,
    detailCategoryId: 6,
    productName: "자두 - 손흥민",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 17,
    regularDiscountRate: 19,
    productPrice: 53923,
    calculatedBasePrice: 44756,
    isRegularSale: "ACTIVE",
    reviewCount: 92,
    averageScore: 1.6,
    soldOut: true,
  },
  {
    productId: 10,
    customerId: 64,
    detailCategoryId: 6,
    productName: "수박 - 손흥민",
    productDescription: "Example Product Description",
    productImage: "path/to/image.jpg",
    baseDiscountRate: 3,
    regularDiscountRate: 26,
    productPrice: 80090,
    calculatedBasePrice: 77687,
    isRegularSale: "ACTIVE",
    reviewCount: 0,
    averageScore: 2.7,
    soldOut: true,
  },
];
